[workspace]
resolver = "2"
members = [
  "pseudo-core",
  "pseudo-cli",
  "pseudo-sys",
  # "pseudo-wasm",
]

[workspace.dependencies]
pseudo-core = { path = "./pseudo-core" }
pseudo-sys = { path = "./pseudo-sys" }
